/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify password and set session cookie on success.
         *
         *     Returns 200 with {"status": "ok"} and sets httpOnly session cookie.
         *     Returns 401 with {"detail": "Invalid password"} on failure.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie.
         *
         *     Returns 200 with {"status": "ok"} and expires the session cookie.
         *     Cookie path is scoped to /m/{mount_code}/ for remote mounts, or / for LAN mode.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clipboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snippets
         * @description Return all clipboard snippets.
         */
        get: operations["list_snippets_api_clipboard__get"];
        put?: never;
        /**
         * Create Snippet
         * @description Create a new snippet and broadcast to all connected devices.
         */
        post: operations["create_snippet_api_clipboard__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clipboard/{snippet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Snippet
         * @description Delete a snippet and broadcast deletion to all connected devices.
         */
        delete: operations["delete_snippet_api_clipboard__snippet_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Snippet Title
         * @description Update snippet title and broadcast to all connected devices.
         */
        patch: operations["update_snippet_title_api_clipboard__snippet_id__patch"];
        trace?: never;
    };
    "/api/file-requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List File Requests
         * @description Return all non-dismissed file requests.
         */
        get: operations["list_file_requests_api_file_requests__get"];
        put?: never;
        /**
         * Create File Request
         * @description Create a new file request and broadcast to other devices.
         */
        post: operations["create_file_request_api_file_requests__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Dismiss File Request
         * @description Dismiss a file request. Only the requester can dismiss.
         */
        delete: operations["dismiss_file_request_api_file_requests__request_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/file-requests/{request_id}/fulfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fulfill File Request
         * @description Fulfill a file request by uploading a file.
         */
        post: operations["fulfill_file_request_api_file_requests__request_id__fulfill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Files
         * @description List files in the shared folder with optional TTL expiry data.
         *
         *     Query parameter 'path' specifies a relative subdirectory.
         *     Empty string means root of the shared folder.
         *     Enriches each file entry with expires_at (ISO timestamp or null).
         */
        get: operations["get_files_api_files_get"];
        put?: never;
        post?: never;
        /**
         * Delete Files
         * @description Delete one or more files or directories.
         *
         *     Accepts JSON body with paths list.
         *     Returns the list of deleted paths.
         */
        delete: operations["delete_files_api_files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Single File
         * @description Download a single file as an attachment.
         *
         *     Returns FileResponse with Content-Disposition: attachment.
         *     Uses filename*=UTF-8'' encoding for unicode support.
         */
        get: operations["download_single_file_api_files_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/download-zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Zip
         * @description Download multiple files as a streaming ZIP archive.
         *
         *     Accepts a JSON body with paths list. Uses zipstream-ng for
         *     memory-efficient streaming without buffering the full archive.
         */
        post: operations["download_zip_api_files_download_zip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview File
         * @description Serve a file inline for preview.
         *
         *     Returns FileResponse with Content-Disposition: inline and
         *     correct Content-Type from mimetypes. Starlette FileResponse
         *     handles Range requests (206 Partial Content) automatically.
         */
        get: operations["preview_file_api_files_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename File
         * @description Rename a file or directory.
         *
         *     Accepts JSON body with path (original) and new_name.
         *     Returns the new relative path.
         */
        patch: operations["rename_file_api_files_rename_patch"];
        trace?: never;
    };
    "/api/files/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Files Endpoint
         * @description Search for files matching query recursively from path.
         *
         *     Query parameter 'q' is the search term (required, non-empty).
         *     Query parameter 'path' is the starting directory (default: root).
         *     Returns SearchResult with matching FileEntry list.
         *
         *     RECEIVE-scoped users get no search results (search results lack the
         *     full path needed to safely scope to own uploads).
         */
        get: operations["search_files_endpoint_api_files_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Files
         * @description Upload one or more files to the specified directory.
         *
         *     Accepts multipart file upload. Optional conflict_resolution query param
         *     controls behavior when file already exists: overwrite, rename, or skip.
         *     Broadcasts toast to WebSocket clients after successful upload.
         */
        post: operations["upload_files_api_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Folder
         * @description Create a new folder.
         *
         *     Accepts JSON body with parent_path and name.
         *     Returns the new folder's relative path.
         */
        post: operations["create_new_folder_api_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/server-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Info
         * @description Return server information including IP, port, URL, and SVG QR code.
         *
         *     In remote mount mode (mount_code set), returns the relay mount URL
         *     instead of local http://ip:port. This ensures the QR code shown in
         *     the client points to the correct relay URL.
         *
         *     If network detection fails, returns ip="unknown", url="unknown",
         *     empty qr_svg, and empty all_ips list.
         */
        get: operations["get_server_info_api_server_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share Upload
         * @description Accept files shared via the PWA Web Share Target API.
         *
         *     Stores each file at the root of the shared folder, auto-renaming on
         *     conflict so the share never fails. Returns a 303 redirect so the
         *     browser navigates back to the SPA after upload.
         *
         *     Args:
         *         files: Multipart files posted by the share sheet. May be empty if
         *             the user shared a URL or text without a file attachment.
         *         x_device_name: Optional device-name header for upload attribution.
         *
         *     Returns:
         *         303 RedirectResponse pointing at ``../`` (resolves to the SPA root
         *         from ``/api/share-upload`` and ``/m/{code}/api/share-upload``).
         *
         *     Raises:
         *         ValueError: When the request contains no files at all.
         */
        post: operations["share_upload_api_share_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Share Links
         * @description List all active (non-expired) share links.
         */
        get: operations["list_share_links_api_shares_get"];
        put?: never;
        /**
         * Create Share Link
         * @description Create a new share link for a file.
         *
         *     Validates that the file exists in the shared folder before creating the link.
         *     Returns 404 if the file does not exist.
         */
        post: operations["create_share_link_api_shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Share Link
         * @description Revoke a share link by token.
         *
         *     Raises ShareLinkNotFoundError (-> 404 centrally) for unknown tokens.
         */
        delete: operations["revoke_share_link_api_shares__token__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Share Page
         * @description Render the share download page for a valid token.
         *
         *     Shows expired page for expired/revoked tokens.
         *     Shows unavailable page if the file was deleted after link creation.
         */
        get: operations["share_page_share__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{token}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Share Download
         * @description Serve the actual file for download via a share link token.
         *
         *     Returns expired page for expired/revoked tokens.
         */
        get: operations["share_download_share__token__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spa Catch All
         * @description Serve SPA index.html (or the placeholder shell) for non-API routes.
         */
        get: operations["spa_catch_all__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_fulfill_file_request_api_file_requests__request_id__fulfill_post */
        Body_fulfill_file_request_api_file_requests__request_id__fulfill_post: {
            /** File */
            file: string;
        };
        /** Body_share_upload_api_share_upload_post */
        Body_share_upload_api_share_upload_post: {
            /** Files */
            files: string[];
        };
        /** Body_upload_files_api_files_upload_post */
        Body_upload_files_api_files_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * ConflictResolution
         * @enum {string}
         */
        ConflictResolution: "overwrite" | "rename" | "skip";
        /**
         * CreateFileRequestPayload
         * @description Request body for creating a new file request.
         */
        CreateFileRequestPayload: {
            /** Description */
            description: string;
        };
        /**
         * CreateFolderRequest
         * @description Request body for creating a new folder.
         */
        CreateFolderRequest: {
            /** Name */
            name: string;
            /** Parent Path */
            parent_path: string;
        };
        /**
         * CreateShareRequest
         * @description Request body for creating a new share link.
         */
        CreateShareRequest: {
            /** File Path */
            file_path: string;
            ttl: components["schemas"]["ShareTTL"];
        };
        /**
         * CreateSnippetRequest
         * @description Request body for creating a new clipboard snippet.
         */
        CreateSnippetRequest: {
            /** Title */
            title: string;
        };
        /**
         * DeleteRequest
         * @description Request body for deleting one or more paths.
         */
        DeleteRequest: {
            /** Paths */
            paths: string[];
        };
        /** DirectoryListing */
        DirectoryListing: {
            /** Entries */
            entries: components["schemas"]["FileEntry"][];
            /** Path */
            path: string;
        };
        /**
         * DownloadZipRequest
         * @description Request body for downloading multiple files as ZIP.
         */
        DownloadZipRequest: {
            /** Paths */
            paths: string[];
        };
        /** FileEntry */
        FileEntry: {
            /** Expires At */
            expires_at?: string | null;
            /** Modified */
            modified: string;
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Size Display */
            size_display: string;
            type: components["schemas"]["FileType"];
        };
        /**
         * FileRequest
         * @description A file request that one device creates for others to fulfill.
         */
        FileRequest: {
            /** Created At */
            created_at: string;
            /** Description */
            description: string;
            /** Fulfilled At */
            fulfilled_at: string | null;
            /** Fulfilled By Device Name */
            fulfilled_by_device_name: string | null;
            /** Fulfilled File Name */
            fulfilled_file_name: string | null;
            /** Fulfilled File Path */
            fulfilled_file_path: string | null;
            /** Id */
            id: string;
            /** Requester Device Id */
            requester_device_id: string;
            /** Requester Device Name */
            requester_device_name: string;
            status: components["schemas"]["RequestStatus"];
        };
        /**
         * FileType
         * @enum {string}
         */
        FileType: "file" | "directory";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Request body for the login endpoint.
         */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /**
         * RenameRequest
         * @description Request body for renaming a file or folder.
         */
        RenameRequest: {
            /** New Name */
            new_name: string;
            /** Path */
            path: string;
        };
        /**
         * RequestStatus
         * @description Status of a file request.
         * @enum {string}
         */
        RequestStatus: "pending" | "fulfilled" | "dismissed";
        /**
         * SearchResult
         * @description Result of a file search operation.
         */
        SearchResult: {
            /** Entries */
            entries: components["schemas"]["FileEntry"][];
            /** Path */
            path: string;
            /** Query */
            query: string;
        };
        /**
         * ServerInfo
         * @description Server information including IP, port, URL, QR code, and mode data.
         */
        ServerInfo: {
            /** Access Mode */
            access_mode?: string | null;
            /** All Ips */
            all_ips: string[];
            /** Current Role */
            current_role?: string | null;
            /** Current User */
            current_user?: string | null;
            /** Hostname */
            hostname: string;
            /** Ip */
            ip: string;
            /** Password Required */
            password_required: boolean;
            /** Port */
            port: number;
            /** Qr Svg */
            qr_svg: string;
            /** Read Only */
            read_only: boolean;
            /** Receive */
            receive: boolean;
            /** Url */
            url: string;
        };
        /**
         * ShareLinkInfo
         * @description Response model for a share link with metadata.
         */
        ShareLinkInfo: {
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string;
            /** File Name */
            file_name: string;
            /** File Path */
            file_path: string;
            /** Share Url */
            share_url: string;
            /** Token */
            token: string;
            /** Ttl Seconds */
            ttl_seconds: number;
        };
        /**
         * ShareTTL
         * @description Time-to-live options for share links, in seconds.
         * @enum {integer}
         */
        ShareTTL: 900 | 3600 | 21600 | 86400;
        /**
         * Snippet
         * @description A clipboard snippet with title and content.
         */
        Snippet: {
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * UpdateSnippetTitleRequest
         * @description Request body for updating snippet title.
         */
        UpdateSnippetTitleRequest: {
            /** Title */
            title: string;
        };
        /**
         * UploadResult
         * @description Result of a single file upload operation.
         */
        UploadResult: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Size Display */
            size_display: string;
            /** Skipped */
            skipped: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_snippets_api_clipboard__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snippet"][];
                };
            };
        };
    };
    create_snippet_api_clipboard__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnippetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snippet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_snippet_api_clipboard__snippet_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snippet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_snippet_title_api_clipboard__snippet_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snippet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSnippetTitleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snippet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_file_requests_api_file_requests__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRequest"][];
                };
            };
        };
    };
    create_file_request_api_file_requests__post: {
        parameters: {
            query?: never;
            header: {
                "x-device-id": string;
                "x-device-name": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFileRequestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_file_request_api_file_requests__request_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-device-id": string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fulfill_file_request_api_file_requests__request_id__fulfill_post: {
        parameters: {
            query?: never;
            header: {
                "x-device-name": string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_fulfill_file_request_api_file_requests__request_id__fulfill_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileRequest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_files_api_files_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_files_api_files_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_single_file_api_files_download_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_zip_api_files_download_zip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadZipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_file_api_files_preview_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_file_api_files_rename_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_files_endpoint_api_files_search_get: {
        parameters: {
            query: {
                q: string;
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_files_api_files_upload_post: {
        parameters: {
            query?: {
                path?: string;
                conflict_resolution?: components["schemas"]["ConflictResolution"] | null;
                ttl?: number | null;
            };
            header?: {
                "x-device-id"?: string | null;
                "x-device-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_folder_api_folders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_info_api_server_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
        };
    };
    share_upload_api_share_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "x-device-name"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_share_upload_api_share_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_share_links_api_shares_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkInfo"][];
                };
            };
        };
    };
    create_share_link_api_shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_share_link_api_shares__token__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_page_share__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_download_share__token__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spa_catch_all__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
